import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const backgroundStyle = {
  backgroundImage: "url(/back_app.png)",
  backgroundSize: "cover", // A imagem cobrirá toda a área

  height: "100%", // A altura será de 100% da janela
  margin: 0, // A altura será de 100% da janela                 // Remove qualquer margem do corpo
  display: "flex", // Para usar flexbox e centralizar conteúdo
  justifyContent: "center", // Centraliza horizontalmente
  alignItems: "center", // Centraliza verticalmente
  backgroundPosition: "top", // A imagem ficará posicionada no topo  
  width: "100%", 
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        style={backgroundStyle}
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}

      </body>
    </html>
  );
}
